version: "3"
services:
    back:
      image: back-aws
      container_name: back
      ports:
        - 8081:8081
      env_file: ./env
      networks:
        - AWS
      
    front:
      build: ./API_Python/front/angular
      ports: 
        - 4200:80
      container_name: front
      env_file: ./env
      networks:
        - AWS
    bdd:
      image: mariadb
      container_name: bdd
      env_file: ./env
      ports:
        - 3306:3306
      networks:
        - AWS
networks:
    AWS:
      name: AWS
      driver: bridge