version: "3.9"
services:
    back:
      image: back-aws
      container_name: back
      ports:
        - 8081:8081
      env_file: ./env
    front:
      image: front-aws
      ports: 
        - 4200:80
      container_name: front
      env_file: ./env
    bdd:
      image: mariadb
      container_name: bdd
      env_file: ./env
      ports:
        - 3306:3306
    adminer:
      image: adminer
      restart: always
      ports:
       - 8082:8080
